// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using angular_test_project.Models;

#nullable disable

namespace angular_test_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220507181258_AddScene")]
    partial class AddScene
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("angular_test_project.Models.Scene", b =>
                {
                    b.Property<int?>("sceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("sceneId"));

                    b.Property<string>("sceneText")
                        .HasColumnType("text");

                    b.HasKey("sceneId");

                    b.ToTable("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
